#!/usr/bin/env bash
#
# A wizard walks a human through a manual procedure, step by step.
# Generated by the /wizard skill.
#
# Everything above the "STAGES" marker is the wizard library: do not hand-edit
# it. Author the per-step stages below the marker.

set -euo pipefail

# ──────────────────────────────────────────────────────────────────────────
# Wizard library: delightful, consistent UX, identical across every wizard.
# ──────────────────────────────────────────────────────────────────────────

if [[ -t 1 ]] && command -v tput >/dev/null 2>&1 && [[ "$(tput colors 2>/dev/null || echo 0)" -ge 8 ]]; then
  BOLD=$(tput bold); DIM=$(tput dim); RESET=$(tput sgr0)
  BLUE=$(tput setaf 4); GREEN=$(tput setaf 2); YELLOW=$(tput setaf 3); RED=$(tput setaf 1)
else
  BOLD=""; DIM=""; RESET=""; BLUE=""; GREEN=""; YELLOW=""; RED=""
fi

# Author sets this at the top of the stages section.
TOTAL_STAGES=0

_STAGE_INDEX=0
ENV_FILE="${ENV_FILE:-.env}"
WRITTEN_ENV=()    # KEYs written to ENV_FILE this run
WRITTEN_SECRET=() # secret NAMEs set this run
SKIPPED=()        # things we couldn't do (e.g. gh missing)

# _clear wipes the terminal so only the current step is on screen. No-op when
# output isn't a terminal, so piped logs stay readable.
_clear() {
  [[ -t 1 ]] || return 0
  if command -v tput >/dev/null 2>&1; then tput clear; else printf '\033[2J\033[3J\033[H'; fi
}

# banner "Title" shows the opening frame: what this wizard does.
banner() {
  _clear
  printf '\n%s%s  %s%s\n' "$BOLD" "$BLUE" "$1" "$RESET"
  printf '%s  %s stages%s\n\n' "$DIM" "$TOTAL_STAGES" "$RESET"
  printf '%s  You drive the browser; this wizard tells you exactly what to do and\n' "$DIM"
  printf '  captures the values you copy back. Stop any time with Ctrl-C and re-run\n'
  printf '  later, since it remembers values already saved.%s\n' "$RESET"
  pause "Ready to start?"
}

# stage "Name" clears the screen, then announces a stage and shows progress.
# Clearing keeps only the current step on screen.
stage() {
  _clear
  _STAGE_INDEX=$((_STAGE_INDEX + 1))
  printf '\n%s%s▸ Stage %s/%s · %s%s\n' \
    "$BOLD" "$BLUE" "$_STAGE_INDEX" "$TOTAL_STAGES" "$1" "$RESET"
}

# say "..." prints a plain instruction line.
say()  { printf '  %s\n' "$1"; }
# step "..." is a numbered-feeling action the human takes in the browser.
step() { printf '  %s•%s %s\n' "$BLUE" "$RESET" "$1"; }
note() { printf '  %s%s%s\n' "$DIM" "$1" "$RESET"; }
warn() { printf '  %s⚠ %s%s\n' "$YELLOW" "$1" "$RESET"; }

# open_url URL opens it in the human's browser, cross-platform incl. WSL.
open_url() {
  local url="$1"
  printf '  %s↗ opening%s %s\n' "$GREEN" "$RESET" "$url"
  { if   command -v wslview     >/dev/null 2>&1; then wslview "$url"
    elif command -v explorer.exe >/dev/null 2>&1; then explorer.exe "$url"
    elif command -v xdg-open    >/dev/null 2>&1; then xdg-open "$url"
    elif command -v open        >/dev/null 2>&1; then open "$url"
    else warn "couldn't open a browser; visit it manually: $url"; fi
  } >/dev/null 2>&1 || warn "couldn't open a browser, so visit it manually: $url"
}

# pause "msg" waits for the human to confirm they've done the manual part.
pause() {
  printf '  %s%s%s ' "$DIM" "${1:-Press Enter to continue}" "$RESET"
  read -r _ || true
}

# confirm "question" is a y/N gate; returns success on yes.
confirm() {
  local reply=""
  printf '  %s? %s [y/N] ' "$YELLOW" "$1"
  read -r reply || true
  [[ "$reply" =~ ^[Yy] ]]
}

# _existing KEY: current value of KEY in ENV_FILE, if any.
_existing() {
  [[ -f "$ENV_FILE" ]] || return 1
  local line; line=$(grep -E "^${1}=" "$ENV_FILE" | tail -n1) || return 1
  printf '%s' "${line#*=}"
}

# ask KEY "Prompt" reads a value into $KEY. Offers the existing .env value as
# a default on re-runs (Enter keeps it). Visible input (non-secret).
ask() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -r input || true
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# ask_secret KEY "Prompt" is like ask, but input is hidden.
ask_secret() {
  local key="$1" prompt="$2" current input
  current=$(_existing "$key" || true)
  if [[ -n "$current" ]]; then
    printf '  %s%s%s %s[Enter keeps current]%s ' "$BOLD" "$prompt" "$RESET" "$DIM" "$RESET"
  else
    printf '  %s%s%s ' "$BOLD" "$prompt" "$RESET"
  fi
  read -rs input || true
  printf '\n'
  [[ -z "$input" && -n "$current" ]] && input="$current"
  printf -v "$key" '%s' "$input"
}

# write_env KEY VALUE upserts KEY=VALUE into ENV_FILE (creates it; replaces
# any existing line). Idempotent.
write_env() {
  local key="$1" value="$2" tmp
  touch "$ENV_FILE"
  tmp=$(mktemp)
  grep -vE "^${key}=" "$ENV_FILE" > "$tmp" || true
  printf '%s=%s\n' "$key" "$value" >> "$tmp"
  mv "$tmp" "$ENV_FILE"
  WRITTEN_ENV+=("$key")
  printf '  %s✓ wrote%s %s → %s\n' "$GREEN" "$RESET" "$key" "$ENV_FILE"
}

# set_secret NAME VALUE sets a GitHub Actions repo secret via gh. Falls back
# to a warning (and records it) if gh is unavailable or unauthenticated.
set_secret() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if printf '%s' "$value" | gh secret set "$name" >/dev/null 2>&1; then
      WRITTEN_SECRET+=("$name")
      printf '  %s✓ set%s GitHub secret %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub secret $name (set it manually: gh secret set $name)")
  warn "skipped GitHub secret $name: gh not ready; set it later"
}

# set_var NAME VALUE sets a GitHub Actions repo variable (non-secret).
set_var() {
  local name="$1" value="$2"
  if command -v gh >/dev/null 2>&1 && gh auth status >/dev/null 2>&1; then
    if gh variable set "$name" --body "$value" >/dev/null 2>&1; then
      printf '  %s✓ set%s GitHub variable %s\n' "$GREEN" "$RESET" "$name"
      return
    fi
  fi
  SKIPPED+=("GitHub variable $name")
  warn "skipped GitHub variable $name, gh not ready; set it later"
}

# finish clears, then shows a closing summary of everything configured.
finish() {
  _clear
  printf '\n%s%s  ✓ Setup complete%s\n' "$BOLD" "$GREEN" "$RESET"
  (( ${#WRITTEN_ENV[@]} ))    && note "wrote ${#WRITTEN_ENV[@]} value(s) to $ENV_FILE: ${WRITTEN_ENV[*]}"
  (( ${#WRITTEN_SECRET[@]} )) && note "set ${#WRITTEN_SECRET[@]} GitHub secret(s): ${WRITTEN_SECRET[*]}"
  if (( ${#SKIPPED[@]} )); then
    printf '\n'; warn "still to do by hand:"
    for s in "${SKIPPED[@]}"; do note "  - $s"; done
  fi
  printf '\n'
}

# ──────────────────────────────────────────────────────────────────────────
# STAGES: author this section. One stage() per step the human takes.
# Replace the example below. Set TOTAL_STAGES to match the stages you write.
# ──────────────────────────────────────────────────────────────────────────

TOTAL_STAGES=7

SCRIPT_DIR=$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)
REPOSITORY_ROOT=$(cd -- "$SCRIPT_DIR/.." && pwd)
RESULT_ROOT="$REPOSITORY_ROOT/artifacts/ticket-13/manual"
SESSION_ID="${SESSION_ID:-win10-$(date +%Y%m%d)}"
ENV_FILE="$RESULT_ROOT/manual-qualification-$SESSION_ID.env"
RESULTS_TSV="$RESULT_ROOT/manual-qualification-$SESSION_ID.tsv"
PICKER_EXECUTABLE="$REPOSITORY_ROOT/artifacts/foundation/picker-win-x64/ModernEmojiPicker.exe"
REPORT_WRITER="$SCRIPT_DIR/write-manual-qualification-report.ps1"
NETWORK_OBSERVER="$SCRIPT_DIR/observe-manual-runtime-network.ps1"
TEST_PAGE="$RESULT_ROOT/manual-target-$SESSION_ID.html"
TEST_TEXT="$RESULT_ROOT/manual-target-$SESSION_ID.txt"
monitor_pid=""

cleanup_manual_session() {
  if [[ -n "$monitor_pid" ]] && kill -0 "$monitor_pid" >/dev/null 2>&1; then
    kill "$monitor_pid" >/dev/null 2>&1 || true
    wait "$monitor_pid" 2>/dev/null || true
  fi
}
trap cleanup_manual_session EXIT

mkdir -p "$RESULT_ROOT"
if [[ ! -f "$RESULTS_TSV" ]]; then
  printf 'Stage\tCaseId\tCase\tResult\tNotes\tEvidence\n' > "$RESULTS_TSV"
fi

single_line() {
  local value="$1"
  value=${value//$'\t'/ }
  value=${value//$'\r'/ }
  value=${value//$'\n'/ }
  printf '%s' "$value"
}

remove_existing_case() {
  local case_id="$1" temporary
  temporary=$(mktemp)
  awk -F '\t' -v id="$case_id" 'NR == 1 || $2 != id' "$RESULTS_TSV" > "$temporary"
  mv "$temporary" "$RESULTS_TSV"
}

record_case() {
  local stage_number="$1" case_id="$2" case_name="$3" evidence="$4"
  local existing result_key result notes
  existing=$(awk -F '\t' -v id="$case_id" 'NR > 1 && $2 == id { print $4; exit }' "$RESULTS_TSV")
  if [[ -n "$existing" ]]; then
    say "$case_name — มีผลเดิม: $existing"
    if confirm "เก็บผลเดิมของกรณีนี้ไว้หรือไม่?"; then
      return
    fi
    remove_existing_case "$case_id"
  fi

  while true; do
    printf '  %sเลือกผล%s [p=ผ่าน, f=ไม่ผ่าน, u=ทำไม่ได้ใน environment, s=ยังไม่ทดสอบ]: ' "$BOLD" "$RESET"
    read -r result_key || true
    case "$result_key" in
      p|P) result="ผ่าน"; break ;;
      f|F) result="ไม่ผ่าน"; break ;;
      u|U) result="ทำไม่ได้ใน environment"; break ;;
      s|S) result="ยังไม่ทดสอบ"; break ;;
      *) warn "กรุณาเลือก p, f, u หรือ s" ;;
    esac
  done

  printf '  %sหมายเหตุ%s (เว้นว่างได้เมื่อผ่าน): ' "$BOLD" "$RESET"
  read -r notes || true
  printf '%s\t%s\t%s\t%s\t%s\t%s\n' \
    "$stage_number" \
    "$(single_line "$case_id")" \
    "$(single_line "$case_name")" \
    "$(single_line "$result")" \
    "$(single_line "$notes")" \
    "$(single_line "$evidence")" >> "$RESULTS_TSV"
  printf '  %s✓ บันทึกผล%s %s\n' "$GREEN" "$RESET" "$case_name"
}

save_stage_evidence() {
  local key="$1" prompt="$2"
  ask "$key" "$prompt"
  write_env "$key" "${!key}"
}

ensure_picker_running() {
  if ! MSYS2_ARG_CONV_EXCL='*' tasklist.exe /FI "IMAGENAME eq ModernEmojiPicker.exe" 2>/dev/null | grep -qi 'ModernEmojiPicker.exe'; then
    "$PICKER_EXECUTABLE" >/dev/null 2>&1 &
    disown || true
    sleep 2
  fi
}

assert_non_elevated_shell() {
  local elevated
  elevated=$(powershell.exe -NoProfile -NonInteractive -Command \
    '$principal = [Security.Principal.WindowsPrincipal]::new([Security.Principal.WindowsIdentity]::GetCurrent()); if ($principal.IsInRole([Security.Principal.WindowsBuiltInRole]::Administrator)) { "true" } else { "false" }' \
    | tr -d '\r')
  if [[ "$elevated" == "true" ]]; then
    warn "terminal นี้เปิดแบบ Administrator ทำให้แอปทดสอบมีสิทธิ์สูงกว่า Modern Emoji Picker และให้ผลลวงว่า Win + . ใช้งานไม่ได้"
    say "ปิด wizard แล้วเปิด PowerShell หรือ Windows Terminal แบบปกติ โดยชื่อหน้าต่างต้องไม่มีคำว่า Administrator จากนั้นรันคำสั่งเดิมอีกครั้ง"
    exit 1
  fi
}

show_tier_a_workflow() {
  local target="$1"
  say "ทดสอบ $target ใน text control จริงตามลำดับนี้"
  step "วาง caret แล้วกด Win + . ตรวจว่า Picker เปิดใกล้ target และรับ focus"
  step "ค้น heart และ หัวใจ; click ต้องส่งแล้วคง Picker, Shift+Enter ต้องส่งแล้วคง Picker"
  step "Enter ต้องส่งแล้วปิด Picker พร้อมกลับ target เดิม"
  step "เปิดใหม่: Esc ใน Search กลับ Browse และ Esc ถัดไปปิด; Browse กด Esc ครั้งเดียวปิด"
  step "เปิดใหม่แล้วคลิกนอก Picker ต้องปิดทันทีและไม่แย่ง focus กลับ"
  step "เปิดใหม่แล้วพิมพ์ข้อความต่อ ตรวจว่า Picker ปิดและอักขระแรกไม่หาย (Typing Handoff)"
  step "ตรวจว่า target ได้ทั้ง Emoji เดี่ยวและ sequence ซับซ้อน โดยไม่มีข้อความหรือ focus ผิดหน้าต่าง"
}

cat > "$TEST_PAGE" <<'HTML'
<!doctype html>
<html lang="th">
<meta charset="utf-8">
<title>Modern Emoji Picker — Manual Target</title>
<style>
body{font:16px system-ui;margin:32px;max-width:900px}textarea{width:100%;height:220px;font-size:28px}pre{padding:16px;background:#eee;white-space:pre-wrap}
</style>
<h1>พื้นที่ทดสอบ Chrome</h1>
<p>วาง caret ในช่องนี้ แล้วใช้ Modern Emoji Picker ข้อมูลด้านล่างจะแสดง Unicode code points ของข้อความที่ได้รับ</p>
<textarea id="target" autofocus></textarea>
<h2>Unicode code points</h2><pre id="points"></pre>
<script>
const target=document.querySelector('#target'), points=document.querySelector('#points');
function update(){points.textContent=Array.from(target.value).map(c=>'U+'+c.codePointAt(0).toString(16).toUpperCase().padStart(4,'0')).join(' ')}
target.addEventListener('input',update);target.focus();
</script>
</html>
HTML
printf 'Modern Emoji Picker manual qualification target\n' > "$TEST_TEXT"

banner "Modern Emoji Picker · Manual qualification"
assert_non_elevated_shell

stage "ตรวจสภาพแวดล้อมและเริ่ม Picker"
say "รายงานของ session นี้จะอยู่ใต้ artifacts/ticket-13/manual และไม่แก้ manual matrix อัตโนมัติ"
if [[ -n "$(git -C "$REPOSITORY_ROOT" status --short)" ]]; then
  warn "working tree ไม่สะอาด กรุณาหยุดและให้ agent ตรวจสอบก่อน หากการเปลี่ยนแปลงไม่ใช่เฉพาะ artifacts"
  if ! confirm "ยืนยันว่าจะดำเนินการต่อกับ working tree ปัจจุบันหรือไม่?"; then exit 1; fi
fi
if [[ ! -x "$PICKER_EXECUTABLE" ]]; then
  warn "ไม่พบ Picker build ที่ $PICKER_EXECUTABLE"
  exit 1
fi
ask TESTER_NAME "ชื่อผู้ทดสอบที่ให้แสดงในรายงาน:"
ask INPUT_LANGUAGE "ภาษา/layout ที่จะใช้ เช่น Thai Kedmanee + English US:"
ask INSERTION_MODE "Insertion mode เริ่มต้น เช่น Hybrid:"
ask REPORTED_DPI "DPI/scale ที่คุณเห็นใน Settings เช่น 100%:"
write_env SESSION_ID "$SESSION_ID"
write_env TESTER_NAME "$TESTER_NAME"
write_env INPUT_LANGUAGE "$INPUT_LANGUAGE"
write_env INSERTION_MODE "$INSERTION_MODE"
write_env REPORTED_DPI "$REPORTED_DPI"
write_env PICKER_EXECUTABLE "$(cygpath -w "$PICKER_EXECUTABLE")"
ensure_picker_running
step "ตรวจว่าไอคอน Modern ปรากฏใน tray และ Classic Picker ยังปิดอยู่"
record_case 1 "environment-preflight" "preflight, identity และ Picker process" "$RESULTS_TSV"

stage "Tier A บนแอปที่มีในเครื่อง"
save_stage_evidence EVIDENCE_STAGE_2 "หลักฐาน Stage 2 เช่น path วิดีโอ/ภาพ หรือ 'สังเกตสดโดยผู้ทดสอบ':"
notepad.exe >/dev/null 2>&1 &
disown || true
show_tier_a_workflow "Notepad"
record_case 2 "tier-a-notepad-win10" "Windows 10 Tier A — Notepad" "$EVIDENCE_STAGE_2"

CHROME_URL="file:///$(cygpath -m "$TEST_PAGE")"
"/c/Program Files/Google/Chrome/Application/chrome.exe" "$CHROME_URL" >/dev/null 2>&1 &
disown || true
show_tier_a_workflow "Chrome (หน้า manual target ที่แสดง code points)"
record_case 2 "tier-a-chrome-win10" "Windows 10 Tier A — Chrome" "$EVIDENCE_STAGE_2"

code "$(cygpath -w "$TEST_TEXT")" >/dev/null 2>&1 &
disown || true
show_tier_a_workflow "VS Code"
record_case 2 "tier-a-vscode-win10" "Windows 10 Tier A — VS Code" "$EVIDENCE_STAGE_2"

explorer.exe "$(cygpath -w "$RESULT_ROOT")" >/dev/null 2>&1 || true
say "ใน Explorer กด Ctrl+L เพื่อ focus address bar แล้วทำ workflow เดียวกัน โดยอย่ากด Enter หลังใส่ Emoji หาก path ไม่ถูกต้อง"
show_tier_a_workflow "Explorer address bar"
record_case 2 "tier-a-explorer-address-win10" "Windows 10 Tier A — Explorer address bar" "$EVIDENCE_STAGE_2"

say "เครื่องนี้ไม่มี Windows Terminal ให้ตรวจยืนยันข้อจำกัด ไม่ต้องติดตั้งเพิ่มใน session นี้"
record_case 2 "tier-a-windows-terminal-win10" "Windows 10 Tier A — Windows Terminal" "$EVIDENCE_STAGE_2"

stage "Keyboard, DPI และ accessibility"
save_stage_evidence EVIDENCE_STAGE_3 "หลักฐาน Stage 3 เช่น path วิดีโอ/ภาพ หรือบันทึก Narrator:"
step "ที่ DPI ปัจจุบัน เปิด Browse/Search เลื่อน grid และเปิด preview ตรวจภาพไม่แตก/ผิดขนาดรุนแรง"
record_case 3 "dpi-current-single-monitor" "DPI ปัจจุบันบนจอเดียว" "$EVIDENCE_STAGE_3"
step "ไม่ใช้เมาส์: ทดสอบ Tab, ลูกศร, Ctrl+F, F1, Alt+T, Alt+Down, Enter, Shift+Enter และ Esc"
record_case 3 "keyboard-only-workflow" "keyboard-only workflow" "$EVIDENCE_STAGE_3"
step "ตรวจ focus indicator ทุก control ใน Light, Dark และ System theme"
record_case 3 "focus-indicator-themes" "focus indicator ใน Light/Dark/System" "$EVIDENCE_STAGE_3"
warn "High Contrast จะเปลี่ยนสีทั้งระบบ บันทึกงานอื่นก่อน แล้วเปิด/ปิดกลับหลังทดสอบ"
step "เปิด Windows High Contrast ตรวจข้อความ, focus, selection, error และปุ่มต่าง ๆ อ่านได้"
record_case 3 "windows-high-contrast" "Windows High Contrast" "$EVIDENCE_STAGE_3"
step "ปิด High Contrast และคืน theme ระบบตามเดิมก่อนทำกรณีถัดไป"
step "เปิด Narrator แล้วตรวจชื่อ tile, selection, busy/queue full และ error state จาก Picker"
record_case 3 "narrator-accessible-state" "Narrator: name/selection/busy/error" "$EVIDENCE_STAGE_3"
say "NVDA และ multi-monitor ต่าง DPI ไม่มีใน environment นี้"
record_case 3 "nvda-accessible-state" "NVDA: name/selection/busy/error" "$EVIDENCE_STAGE_3"
record_case 3 "mixed-dpi-multi-monitor" "สองจอต่าง DPI" "$EVIDENCE_STAGE_3"

stage "Input, Emoji sequence และคิว"
save_stage_evidence EVIDENCE_STAGE_4 "หลักฐาน Stage 4 เช่น path วิดีโอ/ภาพ หรือหน้า Chrome code points:"
say "ใช้ Notepad และหน้า Chrome manual target อย่างน้อยหนึ่งรอบต่อกรณี ตรวจ code points ในหน้า Chrome ไม่ใช้เพียงรูป glyph"
step "ค้น heart แล้วพิมพ์ข้อความอังกฤษต่อทันที ตรวจอักขระแรกไม่หาย"
record_case 4 "input-english-handoff" "English keyboard และ Typing Handoff" "$EVIDENCE_STAGE_4"
step "ค้น หัวใจ แล้วพิมพ์ภาษาไทยต่อทันที ตรวจอักขระแรกไม่หายและไม่มี pre-edit ผิดตำแหน่ง"
record_case 4 "input-thai-ime-handoff" "Thai IME และ Typing Handoff" "$EVIDENCE_STAGE_4"
step "ทดสอบ layout ที่มี dead key ถ้ามี; ห้ามเกิด raw replay หรืออักขระซ้ำ"
record_case 4 "input-dead-key" "dead key commit" "$EVIDENCE_STAGE_4"

declare -a SEQUENCE_CASES=(
  "sequence-single|single code point 😀|😀"
  "sequence-variation-selector|variation selector ❤️|❤️"
  "sequence-skin-tone|skin tone 🙋🏿|🙋🏿"
  "sequence-mixed-tone|mixed tone 🫱🏻‍🫲🏿|🫱🏻‍🫲🏿"
  "sequence-flag|flag 🇹🇭|🇹🇭"
  "sequence-keycap|keycap 1️⃣|1️⃣"
  "sequence-zwj-family|ZWJ family 👨‍👩‍👧|👨‍👩‍👧"
)
for item in "${SEQUENCE_CASES[@]}"; do
  IFS='|' read -r case_id case_name expected <<< "$item"
  step "ส่ง $expected ไป Notepad/Chrome แล้วเทียบ code points กับ sequence ที่คาด"
  record_case 4 "$case_id" "$case_name" "$EVIDENCE_STAGE_4"
done
step "คลิก Emoji ต่างกันอย่างน้อย 10 ตัวอย่างรวดเร็ว ตรวจลำดับปลายทางตรงกับลำดับคลิก"
record_case 4 "queue-rapid-clicks" "rapid clicks ≤ 20 pending" "$EVIDENCE_STAGE_4"
step "สร้าง active + 20 pending แล้วคลิกเพิ่ม ตรวจว่าแสดง queue full และไม่ drop เงียบ"
record_case 4 "queue-full" "queue full" "$EVIDENCE_STAGE_4"
step "ขณะมี active + pending กด Esc ตรวจว่า active จบ, pending ถูกยกเลิก และ focus กลับถูก target"
record_case 4 "queue-dismiss-active" "dismiss ระหว่างส่ง" "$EVIDENCE_STAGE_4"

stage "Clipboard และ target safety"
save_stage_evidence EVIDENCE_STAGE_5 "หลักฐาน Stage 5 เช่น path วิดีโอ/ภาพ, format list หรือ hash:"
say "เปลี่ยน Settings เป็น Paste always เมื่อกรณีต้องบังคับ Temporary Paste และคืนค่าหลังทดสอบ"
warn "ใช้เฉพาะข้อมูลทดสอบที่ไม่สำคัญใน Clipboard แม้ระบบตั้งใจ restore ข้อมูลเดิม"
declare -a CLIPBOARD_CASES=(
  "clipboard-empty|Clipboard ว่าง"
  "clipboard-text|Clipboard Unicode text"
  "clipboard-image|Clipboard image"
  "clipboard-filedrop|Clipboard files (FileDrop)"
  "clipboard-custom|Clipboard custom/private format"
  "clipboard-changed-during-delay|Clipboard เปลี่ยนระหว่าง delay"
  "target-closed-before-validation|target ปิดก่อน validation"
  "target-focus-changed|focus เปลี่ยนไป window อื่น"
  "target-elevated|elevated target จาก non-elevated Picker"
  "explicit-copy|Explicit Copy"
  "clipboard-history|Windows Clipboard History เปิด"
  "clipboard-manager|Clipboard manager ภายนอก"
)
for item in "${CLIPBOARD_CASES[@]}"; do
  IFS='|' read -r case_id case_name <<< "$item"
  step "เตรียมและทดสอบ: $case_name — ตรวจ format/content/focus ก่อนและหลัง ไม่ใช้แค่ Ctrl+V เป็นหลักฐาน"
  record_case 5 "$case_id" "$case_name" "$EVIDENCE_STAGE_5"
done

stage "Privacy และ runtime network 15 นาที"
save_stage_evidence EVIDENCE_STAGE_6 "หลักฐาน packet/firewall audit (path/ชื่อเครื่องมือ) หรือระบุว่าไม่มี:"
NETWORK_REPORT="$RESULT_ROOT/manual-network-$SESSION_ID.json"
NETWORK_LOG="$RESULT_ROOT/manual-network-$SESSION_ID.log"
ensure_picker_running
say "ตัวช่วยจะเก็บ socket observation 15 นาที ระหว่างนี้ให้เปิด/ค้น/preview/Settings/insert หลายครั้ง"
say "อย่าปิด Picker process จนกว่าตัวจับเวลาจะจบ การสังเกต socket ไม่แทน packet capture/firewall audit"
if confirm "พร้อมเริ่มช่วง 15 นาทีหรือไม่?"; then
  pwsh.exe -NoProfile -File "$(cygpath -w "$NETWORK_OBSERVER")" \
    -DurationSeconds 900 \
    -OutputPath "$(cygpath -w "$NETWORK_REPORT")" > "$NETWORK_LOG" 2>&1 &
  monitor_pid=$!
  say "เริ่มแล้ว เวลา $(date '+%H:%M:%S') — กลับมาที่ terminal นี้หลังใช้งานครบ 15 นาที"
  wait "$monitor_pid" || warn "socket observer รายงานข้อผิดพลาด โปรดดู $NETWORK_LOG"
  monitor_pid=""
  say "จบช่วงสังเกตแล้ว หลักฐาน socket: $NETWORK_REPORT"
else
  warn "ข้ามช่วง 15 นาที กรณี privacy ต้องบันทึกเป็นยังไม่ทดสอบ"
fi

PRIVACY_EVIDENCE="$EVIDENCE_STAGE_6; socket=$NETWORK_REPORT"
record_case 6 "privacy-no-outbound" "ไม่มี outbound DNS/TCP/UDP ระหว่าง resident workflow" "$PRIVACY_EVIDENCE"
record_case 6 "privacy-no-telemetry" "ไม่มี update polling/telemetry/analytics/cloud sync" "$PRIVACY_EVIDENCE"
record_case 6 "privacy-no-remote-assets" "ไม่มี remote font/asset call" "$PRIVACY_EVIDENCE"
record_case 6 "privacy-log-disabled" "diagnostic logging ปิด: ไม่มี log content" "$PRIVACY_EVIDENCE"
record_case 6 "privacy-log-enabled-sanitized" "diagnostic logging เปิด: ไม่มีข้อมูลอ่อนไหว" "$PRIVACY_EVIDENCE"

stage "สร้างและตรวจสรุปผล"
say "กำลังสร้าง JSON และ Markdown จากคำตอบที่คุณบันทึก โดยยังไม่แก้ manual matrix"
pwsh.exe -NoProfile -File "$(cygpath -w "$REPORT_WRITER")" \
  -InputPath "$(cygpath -w "$RESULTS_TSV")" \
  -SessionEnvironmentPath "$(cygpath -w "$ENV_FILE")" \
  -OutputDirectory "$(cygpath -w "$RESULT_ROOT")"
say "ผลดิบ: $RESULTS_TSV"
say "ให้ agent review รายงานก่อนนำผลเข้าสู่ docs/qualification/manual-matrices.md"
pause "กด Enter หลังตรวจว่ารายงานถูกสร้างแล้ว"

finish
